---
- name: "Add Java SID Repository"
  register: output
  changed_when: output.changed != true
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ sid main"

- name: "Install Java {{ java_version }}"
  ansible.builtin.package:
    update_cache: false
    name:
      - "openjdk-{{ java_version }}-jdk"

- name: "Verify Java -version, with alternative / default"
  register: java_version_output
  changed_when: java_version_output.rc != 0
  ansible.builtin.command: java -version

- name: "Set Java {{ java_version }} as default version"
  when: java_version_is_default is defined and java_version_is_default and "build " ~ java_version not in java_version_output.stderr
  community.general.alternatives:
    name: "java"
    path: "/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ java_cpu_architecture }}/bin/java"
    priority: 100

- name: "Add a java-{{ java_version }} in /usr/bin and /bin for Java {{ java_version }}"
  loop:
    - "/usr/bin"
    - "/bin"
  loop_control:
    loop_var: java_path
  ansible.builtin.file:
    src: "/usr/lib/jvm/java-{{ java_version }}-openjdk-{{ java_cpu_architecture }}/bin/java"
    dest: "{{ java_path }}/java-{{ java_version }}"
    state: link
    owner: "root"
    group: "root"
    mode: 0711

- name: "Remove Java SID Repository"
  register: output
  changed_when: output.changed != true
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ sid main"
    state: absent
