---
- name: "Add Java SID Repository"
  register: output
  changed_when: output.changed != true
  when: ansible_distribution == "Debian"
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ sid main"

- name: "Install Java"
  retries: 3
  delay: 10
  until: output is success
  ansible.builtin.package:
    update_cache: true
    name:
      - "openjdk-{{ install_java__version }}-jdk"

- name: "Verify Java -version, with alternative / default"
  register: install_java__version_output
  changed_when: install_java__version_output.rc != 0
  ansible.builtin.command: java -version

- name: "Set Java as default version"
  when: install_java__version_is_default is defined and install_java__version_is_default and "build " ~ install_java__version not in install_java__version_output.stderr
  community.general.alternatives:
    name: "java"
    path: "/usr/lib/jvm/java-{{ install_java__version }}-openjdk-{{ install_java__cpu_architecture }}/bin/java"
    priority: 100

- name: "Add a java-version in /usr/bin and /bin for Java {{ install_java__version }}"
  loop:
    - "/usr/bin"
    - "/bin"
  loop_control:
    loop_var: install_java__path
  ansible.builtin.file:
    src: "/usr/lib/jvm/java-{{ install_java__version }}-openjdk-{{ install_java__cpu_architecture }}/bin/java"
    dest: "{{ install_java__path }}/java-{{ install_java__version }}"
    state: link
    owner: "root"
    group: "root"
    mode: "0711"

- name: "Remove Java SID Repository"
  register: output
  changed_when: output.changed != true
  when: ansible_distribution == "Debian"
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ sid main"
    state: absent
