---
- name: "Add Java SID Repository"
  register: output
  changed_when: output.changed != true
  when: ansible_distribution == "Debian"
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ sid main"

- name: "Install Java"
  ansible.builtin.package:
    update_cache: true
    name:
      - "openjdk-{{ instal_java__version }}-jdk"

- name: "Verify Java -version, with alternative / default"
  register: instal_java__version_output
  changed_when: instal_java__version_output.rc != 0
  ansible.builtin.command: java -version

- name: "Set Java as default version"
  when: instal_java__version_is_default is defined and instal_java__version_is_default and "build " ~ instal_java__version not in instal_java__version_output.stderr
  community.general.alternatives:
    name: "java"
    path: "/usr/lib/jvm/java-{{ instal_java__version }}-openjdk-{{ instal_java__cpu_architecture }}/bin/java"
    priority: 100

- name: "Add a java-version in /usr/bin and /bin for Java {{ instal_java__version }}"
  loop:
    - "/usr/bin"
    - "/bin"
  loop_control:
    loop_var: instal_java__path
  ansible.builtin.file:
    src: "/usr/lib/jvm/java-{{ instal_java__version }}-openjdk-{{ instal_java__cpu_architecture }}/bin/java"
    dest: "{{ instal_java__path }}/java-{{ instal_java__version }}"
    state: link
    owner: "root"
    group: "root"
    mode: "0711"

- name: "Remove Java SID Repository"
  register: output
  changed_when: output.changed != true
  when: ansible_distribution == "Debian"
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ sid main"
    state: absent
