---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.install_java"
      tags:
        - "labocbz.install_java"
      vars:
        install_java__version: "17"
        install_java__cpu_architecture: "{{ inv_install_java__cpu_architecture }}"
        install_java__version_is_default: true
      ansible.builtin.include_role:
        name: "labocbz.install_java"
