---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-ubuntu-22"
  gather_facts: false
  tasks:

    - name: "Verify Java -version, with alternative / default"
      register: install_java__version_output
      changed_when: install_java__version_output.rc != 0
      failed_when: "'build {{ inv_install_java__version }}' not in install_java__version_output.stderr"
      ansible.builtin.command: java -version

    - name: "Verify Java -version, with custom binaries for Java {{ inv_install_java__version }}"
      loop:
        - "java-{{ inv_install_java__version }}"
        - "/usr/bin/java-{{ inv_install_java__version }}"
        - "/bin/java-{{ inv_install_java__version }}"
      loop_control:
        loop_var: install_java__call
      register: install_java__version_output
      changed_when: install_java__version_output.rc != 0
      failed_when: "'build {{ inv_install_java__version }}' not in install_java__version_output.stderr"
      ansible.builtin.command: "{{ install_java__call }} -version"
